/**
 * Sound, generated by the browser itself.
 *
 * There are no .mp3 files anywhere in this project on purpose. Audio files are
 * heavy, they are usually copyrighted, and they are the number one reason an
 * offline app fails to load. Instead we ask the browser to make the sounds.
 *
 * What this gives you:
 *   - a slow, warm chord that drifts underneath everything (the "ambient pad")
 *   - a handful of short effects: a chime, a whoosh, a soft thud
 *
 * IMPORTANT RULE OF BROWSERS: audio cannot start until the person taps the
 * screen at least once. That is why `unlock()` exists and why the music starts
 * muted. We are not fighting this rule, we are working with it.
 */

/** The notes of the chord, in hertz. This is a warm, slightly sad A minor 9. */
const CHORD_HZ = [110, 164.81, 220, 329.63, 493.88];

let context: AudioContext | null = null;
let masterGain: GainNode | null = null;
let padVoices: OscillatorNode[] = [];
let padGain: GainNode | null = null;
let isUnlocked = false;

/** Make (or reuse) the one AudioContext for the whole app. */
function getContext(): AudioContext | null {
  if (typeof window === 'undefined') return null;

  if (!context) {
    const AudioContextClass =
      window.AudioContext ??
      (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;

    if (!AudioContextClass) return null;

    context = new AudioContextClass();
    masterGain = context.createGain();
    masterGain.gain.value = 0;
    masterGain.connect(context.destination);
  }

  return context;
}

/**
 * Call this from inside a real tap handler, once. After this, sound works.
 * Calling it more than once is harmless.
 */
export async function unlock(): Promise<void> {
  const ctx = getContext();
  if (!ctx) return;

  if (ctx.state === 'suspended') {
    try {
      await ctx.resume();
    } catch {
      return;
    }
  }

  isUnlocked = true;
}

export function isAudioReady(): boolean {
  return isUnlocked && context !== null;
}

/* ---------------------------------------------------------------------------
 * The ambient pad
 * ------------------------------------------------------------------------ */

/** Start the background chord. Safe to call when it is already playing. */
export function startAmbient(): void {
  const ctx = getContext();
  if (!ctx || padVoices.length > 0) return;

  padGain = ctx.createGain();
  padGain.gain.value = 0.16;

  // A gentle filter takes the harsh edge off, so it sits behind the app
  // rather than on top of it.
  const filter = ctx.createBiquadFilter();
  filter.type = 'lowpass';
  filter.frequency.value = 900;
  filter.Q.value = 0.6;

  padGain.connect(filter);
  filter.connect(masterGain!);

  CHORD_HZ.forEach((frequency, index) => {
    const oscillator = ctx.createOscillator();
    oscillator.type = index === 0 ? 'sine' : 'triangle';
    oscillator.frequency.value = frequency;

    // Each note gets its own slow volume wobble, so the chord breathes
    // instead of sitting perfectly still. This is what stops it sounding
    // like a fire alarm.
    const wobble = ctx.createGain();
    wobble.gain.value = index === 0 ? 0.5 : 0.22;

    const lfo = ctx.createOscillator();
    lfo.frequency.value = 0.05 + index * 0.017;
    const lfoDepth = ctx.createGain();
    lfoDepth.gain.value = 0.12;

    lfo.connect(lfoDepth);
    lfoDepth.connect(wobble.gain);

    oscillator.connect(wobble);
    wobble.connect(padGain!);

    oscillator.start();
    lfo.start();
    padVoices.push(oscillator, lfo);
  });
}

export function stopAmbient(): void {
  padVoices.forEach((voice) => {
    try {
      voice.stop();
    } catch {
      // Already stopped.
    }
  });
  padVoices = [];
  padGain = null;
}

/**
 * Fade the whole app's volume up or down over a couple of seconds.
 * `target` is 0 (silent) to 1 (full).
 */
export function setVolume(target: number, seconds = 1.6): void {
  const ctx = getContext();
  if (!ctx || !masterGain) return;

  const now = ctx.currentTime;
  masterGain.gain.cancelScheduledValues(now);
  masterGain.gain.setValueAtTime(masterGain.gain.value, now);
  masterGain.gain.linearRampToValueAtTime(Math.max(0, Math.min(1, target)), now + seconds);
}

/* ---------------------------------------------------------------------------
 * Short sound effects
 * ------------------------------------------------------------------------ */

type EffectName = 'chime' | 'sparkle' | 'thud' | 'blow' | 'pop';

/**
 * Play a one-off sound. These are deliberately quiet - they should feel like
 * a texture, not a notification.
 */
export function playEffect(name: EffectName): void {
  const ctx = getContext();
  if (!ctx || !isUnlocked || !masterGain) return;

  const now = ctx.currentTime;

  if (name === 'chime' || name === 'sparkle') {
    // A short bell: a few notes of a chord, stacked and decaying.
    const notes = name === 'chime' ? [523.25, 659.25, 783.99] : [880, 1318.5, 1760];

    notes.forEach((frequency, index) => {
      const oscillator = ctx.createOscillator();
      const gain = ctx.createGain();

      oscillator.type = 'sine';
      oscillator.frequency.value = frequency;

      const startAt = now + index * 0.06;
      gain.gain.setValueAtTime(0, startAt);
      gain.gain.linearRampToValueAtTime(0.18, startAt + 0.01);
      gain.gain.exponentialRampToValueAtTime(0.0001, startAt + 1.2);

      oscillator.connect(gain);
      gain.connect(masterGain!);
      oscillator.start(startAt);
      oscillator.stop(startAt + 1.3);
    });
    return;
  }

  if (name === 'pop') {
    const oscillator = ctx.createOscillator();
    const gain = ctx.createGain();
    oscillator.type = 'sine';
    oscillator.frequency.setValueAtTime(180, now);
    oscillator.frequency.exponentialRampToValueAtTime(680, now + 0.07);
    gain.gain.setValueAtTime(0.22, now);
    gain.gain.exponentialRampToValueAtTime(0.0001, now + 0.16);
    oscillator.connect(gain);
    gain.connect(masterGain);
    oscillator.start(now);
    oscillator.stop(now + 0.2);
    return;
  }

  if (name === 'thud') {
    const oscillator = ctx.createOscillator();
    const gain = ctx.createGain();
    oscillator.type = 'sine';
    oscillator.frequency.setValueAtTime(140, now);
    oscillator.frequency.exponentialRampToValueAtTime(48, now + 0.22);
    gain.gain.setValueAtTime(0.3, now);
    gain.gain.exponentialRampToValueAtTime(0.0001, now + 0.3);
    oscillator.connect(gain);
    gain.connect(masterGain);
    oscillator.start(now);
    oscillator.stop(now + 0.32);
    return;
  }

  if (name === 'blow') {
    // Filtered white noise: the sound of a candle going out.
    const length = Math.floor(ctx.sampleRate * 0.5);
    const buffer = ctx.createBuffer(1, length, ctx.sampleRate);
    const channel = buffer.getChannelData(0);
    for (let i = 0; i < length; i += 1) {
      channel[i] = (Math.random() * 2 - 1) * (1 - i / length);
    }

    const source = ctx.createBufferSource();
    source.buffer = buffer;

    const filter = ctx.createBiquadFilter();
    filter.type = 'bandpass';
    filter.frequency.value = 700;

    const gain = ctx.createGain();
    gain.gain.setValueAtTime(0.35, now);
    gain.gain.exponentialRampToValueAtTime(0.0001, now + 0.5);

    source.connect(filter);
    filter.connect(gain);
    gain.connect(masterGain);
    source.start(now);
  }
}

/* ---------------------------------------------------------------------------
 * Listening to her microphone (for blowing out the candles)
 * ------------------------------------------------------------------------ */

export type BlowListener = {
  /** Call this to stop listening and release the microphone. */
  stop: () => void;
};

/**
 * Listen for a sustained puff of air and call `onBlow` when it happens.
 *
 * How it works: we measure how loud the low frequencies are. Blowing across a
 * phone microphone produces a big burst of low-frequency noise, quite unlike
 * speech. We wait for that burst to hold for a few frames so a cough or a
 * door slamming doesn't count.
 *
 * If the microphone is unavailable or she says no to the permission prompt,
 * this returns null and the caller should fall back to a tap button.
 */
export async function listenForBlow(onBlow: () => void): Promise<BlowListener | null> {
  const ctx = getContext();
  if (!ctx || !navigator.mediaDevices?.getUserMedia) return null;

  let stream: MediaStream;
  try {
    stream = await navigator.mediaDevices.getUserMedia({
      audio: { echoCancellation: false, noiseSuppression: false, autoGainControl: false },
    });
  } catch {
    return null;
  }

  await unlock();

  const source = ctx.createMediaStreamSource(stream);
  const analyser = ctx.createAnalyser();
  analyser.fftSize = 1024;
  analyser.smoothingTimeConstant = 0.5;
  source.connect(analyser);

  const bins = new Uint8Array(analyser.frequencyBinCount);
  let sustainedFrames = 0;
  let running = true;
  let frameId = 0;

  const HOW_LOUD_COUNTS = 42; // 0-255. Lower = more sensitive.
  const HOW_LONG_COUNTS = 6; // frames in a row, roughly 100ms

  function check() {
    if (!running) return;

    analyser.getByteFrequencyData(bins);

    // Only look at the bottom eighth of the spectrum - that is where the
    // rumble of moving air lives.
    const lowBins = Math.floor(bins.length / 8);
    let total = 0;
    for (let i = 0; i < lowBins; i += 1) total += bins[i];
    const loudness = total / lowBins;

    if (loudness > HOW_LOUD_COUNTS) {
      sustainedFrames += 1;
      if (sustainedFrames >= HOW_LONG_COUNTS) {
        running = false;
        onBlow();
        return;
      }
    } else {
      sustainedFrames = 0;
    }

    frameId = requestAnimationFrame(check);
  }

  frameId = requestAnimationFrame(check);

  return {
    stop() {
      running = false;
      cancelAnimationFrame(frameId);
      stream.getTracks().forEach((track) => track.stop());
      try {
        source.disconnect();
      } catch {
        // Already disconnected.
      }
    },
  };
}
